//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockchainHashing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blockchain
    {
        public int BlockId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string Nonce { get; set; }
        public string Data { get; set; }
        public string Hash { get; set; }
    }
}
