//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockchainHashing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreviousHash
    {
        public int Id { get; set; }
        public Nullable<int> BlockId { get; set; }
        public string PreviousHash1 { get; set; }
    }
}
